name: alexandrusps
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base
  - r-essentials
  - r-dplyr
  - r-ggplot2
  - r-caret
  - r-reshape2
  - r-ggpubr
  - r-rcolorbrewer
  - r-stringr
  - r-viridis
  - r-rstatix
  - proteinortho
  - perl-app-cpanminus
